# fly.toml app configuration file generated for demo-lexgib on 2025-05-27T17:04:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demo-lexgib'
primary_region = 'waw'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
 
