app = 'demo-lexgib'
primary_region = 'waw'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
